# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Set the resource group name
resourceGroupName='sw'

# Set the SQL server name and admin credentials
sqlServerName='skeda-server'
sqlAdminUsername='skeda-login'
sqlAdminPassword='Simeon@123?'

# Set the SQL database name
sqlDatabaseName='sked'

# Set the App Service name
appServiceName='skeda1'

# Get the connection string for the SQL database
sqlServerFqdn=$(az sql server show --name $sqlServerName --resource-group $resourceGroupName --query fullyQualifiedDomainName -o tsv)
sqlDatabaseConnectionString="Server=$sqlServerFqdn;Database=$sqlDatabaseName;User Id=$sqlAdminUsername;Password=$sqlAdminPassword;Encrypt=true;"

# Configure the App Service with the SQL database connection string
az webapp config connection-string set \
    --name $appServiceName \
    --resource-group $resourceGroupName \
    --connection-string-type SQLAzure \
    --settings 'DbConnectionString'="$sqlDatabaseConnectionString"
